### ISSUE TITLE
Build simple Python GUI

### ISSUE THREAD

**Issue by GregoryNavasarkian** [GregoryNavasarkian/Algebra-App#1]
A simple GUI with basic forms would be nice.

**Comment by GuND0Wn151** [comment]
Hello, So you want a GUI for the respective functions and any specifications like Tkinter etc?

**Comment by GregoryNavasarkian** [comment]
Originally I was going to create a Tkinter GUI with a dropdown for each function with simple input boxes and an enter button. Nothing fancy. Just don't have the time.

**Comment by GuND0Wn151** [comment]
Okay, I will try to work on it, and let you know

**Comment by GuND0Wn151** [comment]
Sorry, was busy in some other project might take time to work on this one.

**Comment by GregoryNavasarkian** [comment]
Went ahead and did it myself
